sim_model:
   joint_state_controller:
        type: "joint_state_controller/JointStateController"
        publish_rate: 50

   base_to_right_motor_controller:
        type: "effort_controllers/JointVelocityController"
        joint: robot_base_to_right_wheel
        pid: {p: 10.0, i: 1.0, d: 1.0}

   base_to_left_motor_controller:
        type: "effort_controllers/JointVelocityController"
        joint: robot_base_to_left_wheel
        pid: {p: 10.0, i: 1.0, d: 1.0}
